# Generated by Django 5.1.5 on 2025-02-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImage/'),
        ),
    ]
